export const requiredPermissions = {
  READ_ALL_USERS: "READ_ALL_USERS",
  READ_USER: "READ_USER",
  UPDATE_USER: "UPDATE_USER",
  CREATE_USER: "CREATE_USER",
  DELETE_USER: "DELETE_USER",
  READ_DEPT: "READ_DEPT",
  UPDATE_DEPT: "UPDATE_DEPT",
  CREATE_DEPT: "CREATE_DEPT",
  DELETE_DEPT: "DELETE_DEPT",
  READ_DIVISION: "READ_DIVISION",
  READ_DOCUMENT: "READ_DOCUMENT",
  UPDATE_DOCUMENT: "UPDATE_DOCUMENT",
  CREATE_DOCUMENT: "CREATE_DOCUMENT",
  DELETE_DOCUMENT: "DELETE_DOCUMENT",
  READ_TRAIL: "READ_TRAIL",
  UPDATE_TRAIL: "UPDATE_TRAIL",
  CREATE_TRAIL: "CREATE_TRAIL",
  DELETE_TRAIL: "DELETE_TRAIL",
  READ_STAFF: "READ_STAFF",
  UPDATE_STAFF: "UPDATE_STAFF",
  CREATE_STAFF: "CREATE_STAFF,",
  DELETE_STAFF: "DELETE_STAFF",
  READ_ROLES: "READ_ROLES",
  UPDATE_ROLES: "UPDATE_ROLES",
  CREATE_ROLES: "CREATE_ROLES,",
  DELETE_ROLES: "DELETE_ROLES",
  READ_PERMISSION: "READ_PERMISSION",
  READ_ARCHIVE: "READ_ARCHIVE",
  UPDATE_ARCHIVE: "UPDATE_ARCHIVE",
  CREATE_ARCHIVE: "CREATE_ARCHIVE",
  DELETE_ARCHIVE: "DELETE_ARCHIVE",
};

export function hasPermission(userPermissions, requiredPermissions) {
  console.log({requiredPermissions});
  return !!requiredPermissions.every(
    (permission) =>
    userPermissions?.find(
        (perm) => perm.permission.permission == permission
      )
  );
}
